name: Delete Old Runs
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Past Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 15
          keep_minimum_runs: 5