name: Validate Action

on:
  push:
    branches:
      - master

jobs:
  build-and-test-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Action
        uses: ./
        with:
          plugin-path: "./code/example"
          plugin-name: "out_stdout2"
