name: Validate Action

on:
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-and-test-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Registry Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Action
        uses: ./
        with:
          plugin-path: "./code/example"
          plugin-name: "out_stdout2"
